baseURL = "http://example.org/"
languageCode = "en-us"
title = "Futurecon SF"
theme = "fcsf21"
relativeURLS = true
[module]
	[[module.mounts]]
		source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
		target = "assets/js/bootstrap.bundle.min.js"
[Params]
	#redirect = "http://futureconsf.com"
	googleTagManager = "GTM-TLCXCPH"