baseURL = "http://example.org/"
languageCode = "en-us"
title = "Futurecon 2021"
theme = "fcsf21"
relativeURLS = true
[module]
	[[module.mounts]]
		source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
		target = "assets/js/bootstrap.bundle.min.js"
	[[module.mounts]]
		source = "node_modules/@fortawesome/fontawesome-free/js/fontawesome.min.js"
		target = "assets/js/fontawesome.min.js"
	[[module.mounts]]
		source = "./node_modules/@fortawesome/fontawesome-free/scss"
		target = "assets/sass/fontawesome"
	[[module.mounts]]
		source = "./node_modules/@fortawesome/fontawesome-free/webfonts"
		target = "static/webfonts"
[Params]
	#redirect = "http://futureconsf.com"
	googleTagManager = "GTM-TLCXCPH"
	tinyLetter = true
	tinyLetterUser = "futureconsf"
	youtube = "futureconsf"
	facebook = ""
	twitter = "futureconsf"
	discord = "8VxFjb5"
[markup.goldmark.renderer] 
	unsafe= true